// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  openrtb

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Source ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Source ) UnmarshalJSON([]byte) error { return nil }
func ( Source ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Source ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Source *Source
