// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  openrtb

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Video ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Video ) UnmarshalJSON([]byte) error { return nil }
func ( Video ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Video ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Video *Video
